theme: jekyll-theme-dinky

title: Data-Driven and Intelligent Cyber-Physical Systems (DI-CPS) for Smart Cities 2022
description: CPS-IoT Week Workshop on Data-Driven and Intelligent Cyber-Physical Systems (DI-CPS) for Smart Cities, 2022
